### ISSUE TITLE
屏幕型号是什么...

### ISSUE THREAD

**Issue by ActivePeter** [peng-zhihui/PocketLCD#1]

**Comment by csr865** [comment]
> _没有提供描述。_

啊这，那怎么办啊😯

**Comment by WillzenZou** [comment]
查了下之前稚晖君之前那个项目，对比了下现在的项目，应该是这个屏幕了：
5.5inch 1080X1920 IPS MIPI AML550L3901 Shenzhen Amelin Electronic Technology Co. Ltd

https://github.com/peng-zhihui/HDMI-PI/tree/main/4.Docs/%E5%B1%8F%E5%B9%95%E8%B5%84%E6%96%99/5.5inch%201080X1920%20IPS%20MIPI%20AML550L3901%20Shenzhen%20Amelin%20Electronic%20Technology%20Co.%20Ltd

**Comment by WillzenZou** [comment]
查了下之前稚晖君之前那个项目，对比了下现在的项目，应该是这个屏幕了：
5.5inch 1080X1920 IPS MIPI AML550L3901 Shenzhen Amelin Electronic Technology Co. Ltd


https://github.com/peng-zhihui/HDMI-PI/tree/main/4.Docs/%E5%B1%8F%E5%B9%95%E8%B5%84%E6%96%99/5.5inch%201080X1920%20IPS%20MIPI%20AML550L3901%20Shenzhen%20Amelin%20Electronic%20Technology%20Co.%20Ltd

**Comment by fzwwj95** [comment]
屏幕型号不确定+只有HEX文件 = 得自己写套驱动吧

**Comment by ActivePeter** [comment]
> 查了下之前稚晖君之前那个项目，对比了下现在的项目，应该是这个屏幕了：
> 5.5inch 1080X1920 IPS MIPI AML550L3901 Shenzhen Amelin Electronic Technology Co. Ltd
> 
> https://github.com/peng-zhihui/HDMI-PI/tree/main/4.Docs/%E5%B1%8F%E5%B9%95%E8%B5%84%E6%96%99/5.5inch%201080X1920%20IPS%20MIPI%20AML550L3901%20Shenzhen%20Amelin%20Electronic%20Technology%20Co.%20Ltd

他也不说一下是哪个手机的屏幕呐==

**Comment by peng-zhihui** [comment]
已经更新了，看README

**Comment by bushiniu** [comment]
物料单有个就好了
