### ISSUE TITLE
大家一起拼pocket-lcd qq群719019471，正在踩坑，年前应该可以发货。满100人就发车

### ISSUE THREAD

**Issue by Professor-Chen** [peng-zhihui/PocketLCD#10]

**Comment by hot36952** [comment]
搜索不到群号

**Comment by Professor-Chen** [comment]
现在可以了

**Comment by tank1293955** [comment]
已提交入群申请。

**Comment by zhanghang1989** [comment]
可以搞个微信群吗，qq现在不让登陆了

**Comment by pengzi007** [comment]
我已经在某宝店铺：**极客出版社** 下单了，你们是一起的吗？

**Comment by zhanghang1989** [comment]
> 我已经在某宝店铺：**极客出版社** 下单了，你们是一起的吗？

👍 这个好，我没办法加群，直接下单了

**Comment by zhoucray** [comment]
我也在这家下单了



---原始邮件---
发件人: "Hang Zhang"<notifications@github.com&gt;
发送时间: 2020年12月4日(周五) 凌晨1:57
收件人: "peng-zhihui/PocketLCD"<PocketLCD@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [peng-zhihui/PocketLCD] 大家一起拼pocket-lcd qq群719019471，正在踩坑，年前应该可以发货。满100人就发车 (#10)




  
我已经在某宝店铺：极客出版社 下单了，你们是一起的吗？
  
👍 这个好，我没办法加群，直接下单了
