### ISSUE TITLE
请问LT6911芯片的固件是需要提前烧录吗？

### ISSUE THREAD

**Issue by 411956158** [peng-zhihui/PocketLCD#13]
尊敬的作者您好，
感谢您分享如此精妙实用的硬件设计，我在diy备料过程中发现LT6911需要烧录固件，请问需要提前烧录好再焊接，还是焊接后通过板载接口烧录程序呢？
希望有幸得到您的回复，不胜感激

**Comment by Mar1n3** [comment]
HDMI_To_MIPI已经预留了IIC烧录接口
![image](https://user-images.githubusercontent.com/8278782/100574293-a83f1100-3314-11eb-8281-b786bfb50119.png)
所以可以焊接好再烧录
参见[烧录说明](https://github.com/peng-zhihui/HDMI-PI/tree/main/4.Docs/%E9%BE%99%E8%AE%AF%E6%96%B9%E6%A1%88)

**Comment by oumaiguo** [comment]
我烧录一直失败 头大

**Comment by he831216** [comment]
<img width="407" alt="image" src="https://github.com/peng-zhihui/PocketLCD/assets/145861631/bbfe5453-a3ad-4a2a-92e1-53a736763443">
这个版本的HDMI转MIPI是不是没准备烧录口啊。
<img width="564" alt="image" src="https://github.com/peng-zhihui/PocketLCD/assets/145861631/f867f6f2-67b5-4898-8e00-8332d90e7cab">
还是通过啥烧录。

**Comment by Lesterbor** [comment]
显示I2C一直离线快自闭了~
