### ISSUE TITLE
烦请稚晖君推荐个10.1-15.6寸的屏幕

### ISSUE THREAD

**Issue by fzwwj95** [peng-zhihui/PocketLCD#20]
想做个便携的的屏幕
作为副屏绘制PCB时候使用，因为也有一些视频编辑、图片PS等需求，笔记本自带屏幕不怎么好。兼顾便携性所以想做个便携的屏幕。
烦请稚晖君安利个10.1-15.6寸的屏幕（100%sRGB、1080p及以上，最好支持DC调光），不知道稚晖君有没这方面的推荐

**Comment by NirViaje** [comment]
> 想做个便携的的屏幕
> 作为副屏绘制PCB时候使用，因为也有一些视频编辑、图片PS等需求，笔记本自带屏幕不怎么好。兼顾便携性所以想做个便携的屏幕。
> 烦请稚晖君安利个10.1-15.6寸的屏幕（100%sRGB、1080p及以上，最好支持DC调光），不知道稚晖君有没这方面的推荐

edp的屏随便挑一块，以前9.7寸有ipad的屏挺好用

**Comment by dandanheng** [comment]
淘宝搜gobigger     

> 想做个便携的的屏幕
> 作为副屏绘制PCB时候使用，因为也有一些视频编辑、图片PS等需求，笔记本自带屏幕不怎么好。兼顾便携性所以想做个便携的屏幕。
> 烦请稚晖君安利个10.1-15.6寸的屏幕（100%sRGB、1080p及以上，最好支持DC调光），不知道稚晖君有没这方面的推荐
