### ISSUE TITLE
关于PCB HDMI_To_MIPI，为什么不直接在PCB上走线连接，而是使用排线连接？

### ISSUE THREAD

**Issue by Jnickcai** [peng-zhihui/PocketLCD#21]
![image](https://user-images.githubusercontent.com/38481926/100894152-26f3a400-34f7-11eb-819b-865b4e693846.png)

**Comment by fzwwj95** [comment]
请认真阅读readme
HDMI转MIPI板子的设计使用了0.5mm的FPC连接线，实际上是可以用PCB走线代替的，我这里这样设计的原因是想留出接口，便于以后扩展调试其它型号的屏幕。当然如果你没有这个需求的话，可以把电路改一下这样焊接和物料都会更省事
