### ISSUE TITLE
好奇为什么不采用东芝的TC358870XBG方案

### ISSUE THREAD

**Issue by fzwwj95** [peng-zhihui/PocketLCD#27]
TC358870XBG方案功能更强大，资料也相对较多，好奇为什么不采用东芝的TC358870XBG方案而选择了龙讯方案呢

**Comment by xiushudongfang** [comment]
请移步 HDMI-PI 项目  那里有说明

**Comment by fzwwj95** [comment]
> 请移步 HDMI-PI 项目 那里有说明

请问HDMI-PI 项目哪里有说明呢？您觉得说明的理由是什么呢？难道是"这个方案的软件我还没有写"吗

**Comment by doublemarkpro** [comment]
个人喜好，up用Plan A做出来并开源已经够可以的了，为什么还有『我觉得plan B更好』『为什么不用plan B』质疑呢……

**Comment by Matthewow** [comment]
> > 请移步 HDMI-PI 项目 那里有说明
> 
> 请问HDMI-PI 项目哪里有说明呢？您觉得说明的理由是什么呢？难道是"这个方案的软件我还没有写"吗

"成本相对较低，芯片外围电路也更简洁"
