### ISSUE TITLE
屏幕

### ISSUE THREAD

**Issue by csr865** [peng-zhihui/PocketLCD#3]
屏幕哪里买？型号或链接🔗，谢谢啦

**Comment by ZinlinCc** [comment]
某宝搜5.5 lcd mipi 出来的就差不多了

**Comment by WillzenZou** [comment]
查了下之前稚晖君之前那个项目，对比了下现在的项目，应该是这个屏幕了：
5.5inch 1080X1920 IPS MIPI AML550L3901 Shenzhen Amelin Electronic Technology Co. Ltd

https://github.com/peng-zhihui/HDMI-PI/tree/main/4.Docs/%E5%B1%8F%E5%B9%95%E8%B5%84%E6%96%99/5.5inch%201080X1920%20IPS%20MIPI%20AML550L3901%20Shenzhen%20Amelin%20Electronic%20Technology%20Co.%20Ltd

**Comment by nineandthreequarters** [comment]
# 关于屏幕、DSI和树莓派
   >树莓派有 **_DSI_** +手机屏幕用 **_DSI_**  ==> 树莓派可以直接连手机拆机屏幕进行显示
- [ ] **这条假设成立吗？**

**Comment by WillzenZou** [comment]
> # 关于屏幕、DSI和树莓派
> > 树莓派有 **_DSI_** +手机屏幕用 **_DSI_**  ==> 树莓派可以直接连手机拆机屏幕进行显示
> 
> * [ ]  **这条假设成立吗？**

理论上可行，要先看硬件和带宽能不能满足(几line)，然后相关驱动和信号线得转接之类的[吃瓜]不过我也不太熟MIPI

**Comment by datidu** [comment]
淘宝上有贵的有便宜的 QAQ 难受了一个一个问吧

**Comment by ActivePeter** [comment]
> 某宝搜5.5 lcd mipi 出来的就差不多了

不同的屏幕初始化指令都不一样。很难通用的

**Comment by peng-zhihui** [comment]
看README，已更新
