### ISSUE TITLE
请问一下各位大佬

### ISSUE THREAD

**Issue by skq7929** [peng-zhihui/PocketLCD#35]
在淘宝上买的CH341T，参照HDMI-MIPI里面的烧录文档烧录固件，一直显示是失败，能确定LT6911C是焊好的，对地值、对应的电压都正确，外部用充电器直接供的5V的电，HDMI线有插上，烧录固件就是一直失败，请问下有没有遇到一样问题的朋友？请问下大佬这大概是哪方面的问题？

**Comment by ZhaoXiangBox** [comment]
我也遇见同样的问题了，有大佬说是IIC 没有上拉电阻，不知道具体是啥原因
