### ISSUE TITLE
关于高亮屏 LED背光电路是否支持42V屏幕

### ISSUE THREAD

**Issue by CmST0us** [peng-zhihui/PocketLCD#38]
自己在定制PocketLCD的屏幕, 用的一块800nit的高亮屏
屏幕LED 电压为 42V 电流 40mA

我查了一下rt9293bj6 的 VOP 为50V, 在 Vref = 300mV 的情况下 Rset = 300mV / 40mA = 7.5欧
我调整电阻Rset到7.5左右之后 发现 LED + ~ LED - 之间的电压只能到 35.6 V

请教一下可能是什么原因

**Comment by CmST0us** [comment]
已找到驱动ic, 成功驱动背光
使用方案 bp1808

**Comment by guanzi008** [comment]
...
