### ISSUE TITLE
关于亚克力中框的疑惑

### ISSUE THREAD

**Issue by Hemistic** [peng-zhihui/PocketLCD#4]
![image](https://user-images.githubusercontent.com/53587394/100530057-4903d280-3228-11eb-92f7-ff2e431b2f6f.png)
![image](https://user-images.githubusercontent.com/53587394/100530075-781a4400-3228-11eb-95d3-8f9fe57339d7.png)

为什么这里的hdmi接口是封闭的，还是我打开的方式不对？

**Comment by fzwwj95** [comment]
是封闭的，通过分层+双面雕刻，最后叠在一起实现的

**Comment by fzwwj95** [comment]
三层的叠加效果
![image](https://user-images.githubusercontent.com/17897415/100530589-d2b69e80-322e-11eb-9dcb-a0570bc56579.png)

**Comment by Hemistic** [comment]
> 三层的叠加效果
> ![image](https://user-images.githubusercontent.com/17897415/100530589-d2b69e80-322e-11eb-9dcb-a0570bc56579.png)

懂了，谢谢

**Comment by tth1996** [comment]
![image](https://user-images.githubusercontent.com/8278782/100537705-a66a4480-3265-11eb-81d1-2b05e490aade.png)
我觉得稚辉君打的板子不是1.6mm的 图片上看起来略薄 而且他在最上面一层加了一张PCB小板以弥补屏幕的厚度方便贴膜

**Comment by peng-zhihui** [comment]
板子厚度再PCB堆栈设置里可以看到的，都是1mm，然后上面是加了一小块1.6mm的PCB正好和屏幕等高。中框的加工是切成两块，其中一块2D切割，另一块如视频里所述是正反两面雕刻的，最后组装到一起。

**Comment by Hemistic** [comment]
> 板子厚度再PCB堆栈设置里可以看到的，都是1mm，然后上面是加了一小块1.6mm的PCB正好和屏幕等高。中框的加工是切成两块，其中一块2D切割，另一块如视频里所述是正反两面雕刻的，最后组装到一起。

可以问一下板上的栅格开口是不是给喇叭box的？如果是，那是什么型号呢？
