### ISSUE TITLE
屏幕型号、BOM表

### ISSUE THREAD

**Issue by ClimbSnail** [peng-zhihui/PocketLCD#5]
不知道具体是哪个屏幕，应该不是通用的吧？如果生成一个BOM表就更好了

**Comment by WillzenZou** [comment]
屏幕稚晖君之前另一个项目有，还有一个10.1寸屏的固件
查了下之前稚晖君之前那个项目，对比了下现在的项目，应该是这个屏幕了：
5.5inch 1080X1920 IPS MIPI AML550L3901 Shenzhen Amelin Electronic Technology Co. Ltd

https://github.com/peng-zhihui/HDMI-PI/tree/main/4.Docs/%E5%B1%8F%E5%B9%95%E8%B5%84%E6%96%99/5.5inch%201080X1920%20IPS%20MIPI%20AML550L3901%20Shenzhen%20Amelin%20Electronic%20Technology%20Co.%20Ltd

**Comment by tansirui** [comment]
> 屏幕稚晖君之前另一个项目有，还有一个10.1寸屏的固件
> 查了下之前稚晖君之前那个项目，对比了下现在的项目，应该是这个屏幕了：
> 5.5inch 1080X1920 IPS MIPI AML550L3901 Shenzhen Amelin Electronic Technology Co. Ltd
> 
> https://github.com/peng-zhihui/HDMI-PI/tree/main/4.Docs/%E5%B1%8F%E5%B9%95%E8%B5%84%E6%96%99/5.5inch%201080X1920%20IPS%20MIPI%20AML550L3901%20Shenzhen%20Amelin%20Electronic%20Technology%20Co.%20Ltd

你好，请问你找到谁家卖这款屏幕吗？可以找到这个屏幕的厂家官网，但是没有购买链接。

**Comment by WillzenZou** [comment]
> > 屏幕稚晖君之前另一个项目有，还有一个10.1寸屏的固件
> > 查了下之前稚晖君之前那个项目，对比了下现在的项目，应该是这个屏幕了：
> > 5.5inch 1080X1920 IPS MIPI AML550L3901 Shenzhen Amelin Electronic Technology Co. Ltd
> > https://github.com/peng-zhihui/HDMI-PI/tree/main/4.Docs/%E5%B1%8F%E5%B9%95%E8%B5%84%E6%96%99/5.5inch%201080X1920%20IPS%20MIPI%20AML550L3901%20Shenzhen%20Amelin%20Electronic%20Technology%20Co.%20Ltd
> 
> 你好，请问你找到谁家卖这款屏幕吗？可以找到这个屏幕的厂家官网，但是没有购买链接。

找到了，还有TYPE-C驱动板全套的，300左右
另外淘宝上或者阿里巴巴搜FRD550L3901能找到80左右的单屏幕，但是邮费贵

**Comment by Liunkwww** [comment]
> > 屏幕稚晖君之前另一个项目有，还有一个10.1寸屏的固件
> > 查了下之前稚晖君之前那个项目，对比了下现在的项目，应该是这个屏幕了：
> > 5.5inch 1080X1920 IPS MIPI AML550L3901 Shenzhen Amelin Electronic Technology Co. Ltd
> > https://github.com/peng-zhihui/HDMI-PI/tree/main/4.Docs/%E5%B1%8F%E5%B9%95%E8%B5%84%E6%96%99/5.5inch%201080X1920%20IPS%20MIPI%20AML550L3901%20Shenzhen%20Amelin%20Electronic%20Technology%20Co.%20Ltd
> 
> 你好，请问你找到谁家卖这款屏幕吗？可以找到这个屏幕的厂家官网，但是没有购买链接。

官方淘宝店有，但邮费略贵
https://item.taobao.com/item.htm?spm=a1z10.3-c.w4002-18603147148.13.1e9e4b9fGSY1En&id=543793236047

**Comment by peng-zhihui** [comment]
看README，已更新
