### ISSUE TITLE
可调电阻R6的范围是多大啊?

### ISSUE THREAD

**Issue by ZinlinCc** [peng-zhihui/PocketLCD#6]
这个电阻接反馈应该是限流用的。但是这个范围你们觉得应该买多大。是不是差不多几K就够用了？

**Comment by WillzenZou** [comment]
> 这个电阻接反馈应该是限流用的。但是这个范围你们觉得应该买多大。是不是差不多几K就够用了？

应该够了，这个是调亮度的，阻值越小，亮度越大来着，我看手册看到的。
![-472199e77d6fbef6](https://user-images.githubusercontent.com/74403153/100536477-d280c800-325b-11eb-88cd-11c176f03d17.jpg)
![-68f33ed9dcb526ec](https://user-images.githubusercontent.com/74403153/100536480-d6ace580-325b-11eb-8a4c-c9ee40d68028.jpg)

**Comment by tth1996** [comment]
![image](https://user-images.githubusercontent.com/8278782/100537542-71a9bd80-3264-11eb-9ffc-4df3b594bcef.png)
推荐的阻值是15欧

**Comment by peng-zhihui** [comment]
10R够用
